# Generated by Django 4.2.4 on 2023-08-21 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.photo', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.DateField(auto_now=True, verbose_name='дата публикации фото'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_comment', models.DateField(auto_now=True, verbose_name='дата публикации комментария')),
                ('text_comment', models.TextField(verbose_name='текст комментария')),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('image_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.photo', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comment',
            },
        ),
    ]
