# Generated by Django 4.2.4 on 2023-09-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
