# Generated by Django 4.2.4 on 2024-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_photo_author_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='boolean_value',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
