# Generated by Django 4.2.4 on 2024-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_likes_boolean_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_comment',
            field=models.TextField(max_length=20, verbose_name='Имя'),
        ),
    ]
