# Generated by Django 4.2.4 on 2024-02-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_comment_author_comment_alter_likes_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='ip',
        ),
    ]
